language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- travis_wait npm install
script:
- npm run test
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/token-migration.aepps.com/
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh deploy@139.59.142.164 "mkdir -p /var/www/html/BRANCHES.token-migration.aepps.com/`echo $TRAVIS_BRANCH | tr '[:punct:]' '-'`/" && rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/BRANCHES.token-migration.aepps.com/`echo $TRAVIS_BRANCH | tr '[:punct:]' '-'`
  on:
    all_branches: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_d9a888dfcdad_key -iv $encrypted_d9a888dfcdad_iv
  -in deploy.enc -out deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy
- ssh-add deploy
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
